import 'package:flunancier/models/transaction_category.dart';
import 'package:flutter/material.dart';

/// Catégorie pour une dépense
const expenseCategories = [
  TransactionCategory(
    name: "Habitation",
    color: Colors.purple,
    type: TypeTransaction.expenses,
    subCategory: [
      TransactionCategory(
        name: "Travaux",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.handyman_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Electricité, gaz, eau",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.bolt_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Taxes",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.account_balance_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Loyer",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.home_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Assurance",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.paid_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Ménage",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.cleaning_services_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Ameublement",
        color: Colors.purple,
        type: TypeTransaction.expenses,
        icon: Icons.chair_alt_outlined,
        subCategory: [],
      ),
    ],
    icon: Icons.home_work_outlined,
  ),
  TransactionCategory(
    name: "Loisirs",
    color: Colors.deepPurple,
    type: TypeTransaction.expenses,
    icon: Icons.games_outlined,
    subCategory: [
      TransactionCategory(
        name: "Multimédia",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.mouse_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Vacances",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.holiday_village_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Animaux",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.pets_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Sport",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.fitness_center_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Sorties",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.local_bar_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Cadeaux",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.card_giftcard_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Événement",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.confirmation_number_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Jeux",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.sports_esports_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Hôtels/Gites",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.hotel_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Livres",
        color: Colors.deepPurple,
        type: TypeTransaction.expenses,
        icon: Icons.book_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Communications",
    color: Colors.blueGrey,
    type: TypeTransaction.expenses,
    icon: Icons.phone_outlined,
    subCategory: [
      TransactionCategory(
        name: "Téléphone",
        color: Colors.blueGrey,
        type: TypeTransaction.expenses,
        icon: Icons.phone_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Internet/TV",
        color: Colors.blueGrey,
        type: TypeTransaction.expenses,
        icon: Icons.router_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Alimentation",
    color: Colors.blue,
    type: TypeTransaction.expenses,
    icon: Icons.restaurant_outlined,
    subCategory: [
      TransactionCategory(
        name: "Courses",
        color: Colors.blue,
        type: TypeTransaction.expenses,
        icon: Icons.shopping_cart_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Restaurant",
        color: Colors.blue,
        type: TypeTransaction.expenses,
        icon: Icons.restaurant_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Cantine",
        color: Colors.blue,
        type: TypeTransaction.expenses,
        icon: Icons.brunch_dining_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Transport",
    color: Colors.brown,
    type: TypeTransaction.expenses,
    icon: Icons.commute_outlined,
    subCategory: [
      TransactionCategory(
        name: "Véhicule",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.directions_car_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Moto",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.two_wheeler_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Péages",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.directions_car_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Essence",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.local_gas_station_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Location véhicule",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.car_rental_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Assurance",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.paid_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Parking",
        color: Colors.brown,
        type: TypeTransaction.expenses,
        icon: Icons.local_parking_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Santé/Bien-être",
    color: Colors.cyan,
    type: TypeTransaction.expenses,
    icon: Icons.healing_outlined,
    subCategory: [
      TransactionCategory(
        name: "Soin du corps",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.spa_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Services à la personne",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.medical_services_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Mutuelle",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.medical_services_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Pharmacie",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.local_pharmacy_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Assurance",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.medical_services_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Médecin",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.medical_services_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Hopital",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.local_hospital_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Coiffeur",
        color: Colors.cyan,
        type: TypeTransaction.expenses,
        icon: Icons.content_cut_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Habillement",
    color: Colors.pinkAccent,
    type: TypeTransaction.expenses,
    icon: Icons.checkroom_outlined,
    subCategory: [
      TransactionCategory(
        name: "Vêtements",
        color: Colors.pinkAccent,
        type: TypeTransaction.expenses,
        icon: Icons.checkroom_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Chaussures",
        color: Colors.pinkAccent,
        type: TypeTransaction.expenses,
        icon: Icons.checkroom_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Accessoires",
        color: Colors.pinkAccent,
        type: TypeTransaction.expenses,
        icon: Icons.checkroom_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Finances",
    color: Colors.red,
    type: TypeTransaction.expenses,
    icon: Icons.attach_money,
    subCategory: [
      TransactionCategory(
        name: "Impôts",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.account_balance_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Epargne",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.savings_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Prêts",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.payments_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Frais bancaires",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.payment_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Assurance vie",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.loyalty_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Bourse",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.currency_exchange_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Retrait d'argent",
        color: Colors.red,
        type: TypeTransaction.expenses,
        icon: Icons.local_atm_outlined,
        subCategory: [],
      ),
    ],
  ),
  TransactionCategory(
    name: "Autres",
    color: Colors.yellow,
    type: TypeTransaction.expenses,
    icon: Icons.local_atm_outlined,
    subCategory: [
      TransactionCategory(
        name: "Frais professionel",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.card_travel_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Enfants",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.stroller_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Amendes",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.local_police_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Frais de justice",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.gavel_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Frais de scolarité",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.school_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Gardes d'enfant",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.baby_changing_station_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Dons",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.volunteer_activism_outlined,
        subCategory: [],
      ),
      TransactionCategory(
        name: "Autres dépenses",
        color: Colors.yellow,
        type: TypeTransaction.expenses,
        icon: Icons.local_atm_outlined,
        subCategory: [],
      ),
    ],
  ),
];

/// Catégorie pour un revenu
const incomeCategories = [
  TransactionCategory(
    name: "Salaires",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.account_balance_wallet_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Assurance Maladie",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.health_and_safety_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Remboursement frais pro",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.card_travel_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Revenu foncier",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.real_estate_agent_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Allocations familliales",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.family_restroom_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Rentes et pensions",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.payments_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Dividendes et plus-values",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.savings_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Cadeaux",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.card_giftcard_outlined,
    subCategory: [],
  ),
  TransactionCategory(
    name: "Autres revenus",
    color: Colors.green,
    type: TypeTransaction.income,
    icon: Icons.local_atm_outlined,
    subCategory: [],
  ),
];
